microservices-umbrella-chart:
  deployment:
    container:
      cpuLimit: 1
      cpuRequest: 0.5
      digest: sha256:be8343285e8a6e9aed9a0df5d711107fb9c5a207e3686ccce7c892dd4353eff2
      env:
        - name: ENVIRONMENT
          value: DEBUG
        - name: REDIS_HOST
          value: redis-master.databases
        - name: REDIS_PORT
          value: "6379"
        - name: VIDEOS_API_HOST
          value: "videos-api.microservices"
        - name: VIDEOS_API_PORT
          value: "10010"
      healthPath: /healthz
      image: ahmedgrati/playlist-ms
      memoryLimit: 500Mi
      memoryRequest: 500Mi
      name: playlist-api-container
      port: 10010
    name: playlist-api
    namespace: microservices
    replicas: 1
  serviceAccount:
    name: playlist-api-sa

  service:
    name: playlist-api
    type: ClusterIP
    ports:
      - protocol: TCP
        name: http
        port: 80
        targetPort: 10010
  
