global:
  namespace: microservices
microservices-umbrella-chart:
  deployment:
    initContainer:
      name: data-seed
      image: ahmedgrati/data-seed-job
      digest: sha256:5ffd38163485b189e8824c01a61f174a118c9c9555c618728f2be85e2a32b025
      env:
        - name: MICROSERVICE
          value: playlist
        - name: REDIS_HOST
          value: redis-master.databases
        - name: REDIS_PORT
          value: "6379"
    container:
      cpuLimit: 1
      cpuRequest: 0.5
      image: ahmedgrati/playlist-ms
      digest: sha256:17e039422b15810a01286525266598d1eaa3c06ee4225516ce738c5be96b8e43
      env:
        - name: ENVIRONMENT
          value: DEBUG
        - name: REDIS_HOST
          value: redis-master.databases
        - name: REDIS_PORT
          value: "6379"
        - name: VIDEOS_API_HOST
          value: "videos-api.microservices"
        - name: VIDEOS_API_PORT
          value: "10010"
      healthPath: /healthz
      memoryLimit: 500Mi
      memoryRequest: 500Mi
      name: playlist-api-container
      port: 10010
    name: playlist-api
    namespace: microservices
    replicas: 1
  serviceAccount:
    name: playlist-api-sa

  service:
    name: playlist-api
    type: ClusterIP
    ports:
      - protocol: TCP
        name: http
        port: 80
        targetPort: 10010
  
