microservices-umbrella-chart:
  deployment:
    container:
      cpuLimit: 1
      cpuRequest: 0.5
      digest: sha256:d8ea43bf8dbc045df14a1b6b58c4927f9df3f67ff952fe5edb571cc8f9192674
      env:
        - name: ENVIRONMENT
          value: DEBUG
        - name: REDIS_HOST
          value: playlists-db
        - name: REDIS_PORT
          value: "6379"
      healthPath: /
      image: aimvector/service-mesh
      memoryLimit: 500Mi
      memoryRequest: 500Mi
      name: playlist-api-container
      port: 5000
    name: playlist-api
    namespace: microservices
    replicas: 1
  serviceAccount:
    name: playlist-api-sa
