global:
  namespace: microservices
  databasePasswordSecret: redis-secret
microservices-umbrella-chart:
  deployment:
    initContainer:
      name: data-seed
      image: ahmedgrati/data-seed-job
      digest: sha256:5ffd38163485b189e8824c01a61f174a118c9c9555c618728f2be85e2a32b025
    container:
      cpuLimit: 1
      cpuRequest: 0.5
      image: ahmedgrati/playlist-ms
      digest: sha256:642239cd1ce82bb518420d2ced2552e517c0a4016815c0a810f2c6b352b39ebe
      probe:
        readinessProbe:
          port: 10010
          path: /healthz
        livenessProbe:
          port: 10010
          path: /healthz
      memoryLimit: 500Mi
      memoryRequest: 500Mi
      name: playlist-api-container
      ports:
        - name: application
          port: 10010
        - name: metrics
          port: 8000
    name: playlist-api
    namespace: microservices
    replicas: 1
  serviceAccount:
    name: playlist-api-sa

  service:
    name: playlist-api
    type: ClusterIP
    ports:
      - protocol: TCP
        name: http
        port: 80
        targetPort: 10010
      - protocol: TCP
        name: metrics
        port: 8000
        targetPort: 8000

  configmap:
    name: playlist-env
    data:
      ENVIRONMENT: DEBUG
      REDIS_HOST: redis-master.databases
      REDIS_PORT: 6379
      VIDEOS_API_HOST: videos-api.microservices
      VIDEOS_API_PORT: 10010
      JAEGER_ENDPOINT: http://jaeger-collector.monitoring:14268/api/traces

  initConfigMap:
    name: data-seed-env
    data:
      MICROSERVICE: playlist
      REDIS_HOST: redis-master.databases
      REDIS_PORT: 6379
  monitoring:
    enabled: true
    interval: 20s
    targetPort: metrics
    path: /
