name: Helm Chart CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Generate Dependencies
        run: make dependencies
      - name: Generate Kubernetes YAML Files
        run: make template > application.yaml
      - name: Run Checkov Analysis
        uses: bridgecrewio/checkov-action@master
        id: checkov
        with:
          file: application.yaml
          quiet: true
          framework: kubernetes
          output_format: sarif
          output_file_path: reports/results.sarif
          download_external_modules: true